let a=2, b=6
console.log("area of rectangle is")
console.log(a*b)
console.log("area of sqaure with side a=2")
console.log(a*a)
console.log("area of circle with radius a=2")
console.log(3.14*a*a)
console.log("area of triangle with base a and height b")
console.log(0.15*a*b)
console.log("perimeter of circle with radius a")
console.log(2*3.14*a)
console.log("volume of cube with side a")
console.log(a**3)